---
- name: Demo one - To fetch the details
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Upload public key to AWS
      ec2_key:
        name: test1-key 
        key_material: "{{ lookup('file', '/home/student/project/sshkey.pub') }}"
        region: ap-southeast-1 
        aws_access_key: AKIA3Z762TCTEEQPGXWH 
        aws_secret_key: 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 

...
