- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
     key_name: aws_instance_Ansible
     instance_type: t2.micro
     image: ami-082105f875acab993
     region: ap-southeast-1
     wait: yes
     group: default
     count: 1
     vpc_subnet_id: default
     assign_public_ip: yes
     aws_access_key: AKIA3Z762TCTEEQPGXWH
     Aws_secret_key: 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
